#ifndef QEASYSHELL_GLOBAL_H
#define QEASYSHELL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QEASYSHELL_LIBRARY)
#  define QEASYSHELLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QEASYSHELLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QEASYSHELL_GLOBAL_H
